apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata:
  name: nginx-ingress
  namespace: kube-system
spec:
  chart: stable/nginx-ingress
  set:
    rbac.enabled: "true"
    ssl.enabled: "true"